### ISSUE TITLE
Plock images in rows

### ISSUE THREAD

**Issue by erksdee** [askides/react-plock#36]
Hi, 

Thank you for this fantastic library. Are we able to plock images in rows?

**Comment by askides** [comment]
Hello!

Do you have an example of what are you talking about?

**Comment by erksdee** [comment]
Hey @askides, please see attached example.

<img width="317" alt="Screen Shot 2023-09-27 at 7 10 23 pm" src="https://github.com/askides/react-plock/assets/7500305/0383dde0-f88c-414b-9024-72a1045c616c">
