### ISSUE TITLE
How to switch columns by state?

### ISSUE THREAD

**Issue by crapthings** [askides/react-plock#44]
Image missing in list after change columns?

**Comment by askides** [comment]
Hello, can you provide an example of the problem please?

**Comment by gazdagergo** [comment]
Hello, I'm reopening this issue because the title matches my problem. I'm trying to switch between list and card views by updating the configuration on state change, but it doesn't seem to affect the layout. What could be preventing the rerender? Thanks!

```
const [selectedView, setView] = useState('card')

...

return (
  <Masonry
    ...
    config={selectedView === 'card' ? {
      columns: [1, 2, 3, 4],
      gap: [24, 24, 24, 32],
      media: [520, 640, 1024, 1200]
    } : {
      columns: 1,
      gap: 24,
    }}
  >
)
