### ISSUE TITLE
feature: Adding parent element config options

### ISSUE THREAD

**Issue by JinmuGo** [askides/react-plock#47]
hi i'm using your library very well thank you! :)
 
what about adding alternative element instead of “div” for semantic tagging?

for example, in the config object be like

```js
const config = {
 parent: article
}

<Masonry
   config={config}
   // ...etc...
 />
```

and Masonry Wrapper is set as "article" html element not "div"

please consider this option thank you

**Comment by askides** [comment]
Hi @JinmuGo!

The `as` property now is [available in v3.3.0](https://github.com/askides/react-plock/commit/9f0d88f)!

```tsx
<Masonry as="article" />
```
